name: install playwright
description: installs and caches playwright

runs:
  using: composite
  steps:
    - shell: bash
      run: echo "PLAYWRIGHT_VERSION=$(jq -r '.devDependencies.playwright' package.json)" >> $GITHUB_ENV

    - uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5
      id: playwright-cache
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ runner.os }}-${{ env.PLAYWRIGHT_VERSION }}

    - shell: bash
      run: pnpm playwright install --with-deps chromium
