name: install playwright
description: installs and caches playwright

runs:
  using: composite
  steps:
    - shell: bash
      run: echo "PLAYWRIGHT_VERSION=$(jq -r '.devDependencies.playwright' package.json)" >> $GITHUB_ENV

    - uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6
      id: playwright-cache
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ runner.os }}-${{ env.PLAYWRIGHT_VERSION }}

    - shell: bash
      run: pnpm playwright install --with-deps chromium
