name: install playwright
description: installs and caches playwright

runs:
  using: composite
  steps:
    - shell: bash
      run: echo "PLAYWRIGHT_VERSION=$(jq -r '.devDependencies.playwright' package.json)" >> $GITHUB_ENV

    - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
      id: playwright-cache
      with:
        path: ~/.cache/ms-playwright
        key: playwright-${{ runner.os }}-${{ env.PLAYWRIGHT_VERSION }}

    - shell: bash
      run: pnpm playwright install --with-deps chromium
